version: '3'
services:
  srt-server-defect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888/udp
  srt-server-working:
    build: 
      context: .
      dockerfile: Dockerfile.working
    ports:
      - 8887:8888/udp